### ISSUE TITLE
FMRC Download index file for <dataset>

### ISSUE THREAD

**Issue by rjdave** [Unidata/tds#238]
THREDDS-5.4-SNAPSHOT from 05-13-2022
CentOS 7, AdoptOpenJDK 11.0.15+10, Tomcat 8.5.75

When using the `admin/debug` interface and navigating to the `admin/collection/showCollection` page for a given dataset, there is a "Download index file for _datasetName_" link. However, clicking the link always gives the error:

`_datasetName_ NOT FOUND`

even for a working fully updated FMRC dataset.

**Comment by rjdave** [comment]
THREDDS-5.5-SNAPSHOT from 07-26-2022
CentOS 7, AdoptOpenJDK 11.0.15+10, Tomcat 8.5.75

I tested the latest snapshot and I get the same error. There is no further information in `threddsServlet.log`:

```
2022-08-04T14:45:58.213 -0400 [    315624][      10] INFO  - threddsServlet - Remote host: 192.168.30.10 - Request: "GET /thredds/admin/collection/download?collection=13MHz_2km_realtime_codar_fmrc HTTP/1.1"
2022-08-04T14:45:58.270 -0400 [    315681][      10] INFO  - threddsServlet - Request Completed - 404 - -1 - 57
```

**Comment by tdrwenski** [comment]
Hi David,

In TDS 5, the FMRC datasets no longer have an xml index file (the persistence is now handled by ChronicleMap). The admin service "download index" only works for downloading grib index files, so the "not found" error is due to the admin service looking for a grib index for your FMRC dataset which of course does not exist.

**Comment by rjdave** [comment]
None of my datasets are grib so that explains it.
