### ISSUE TITLE
Which threddsConfig.xml is up-to-date?

### ISSUE THREAD

**Issue by rjdave** [Unidata/tds#262]
Current github code

The TDS source code has 2 examples of the `threddsConfig.xml` file: one in `tds/src/main/webapp/WEB-INF/altContent/startup` and one in `tds/src/test/content/thredds`. The two files are very inconsistent with each other. In particular, the file in `tds/src/main/webapp/WEB-INF/altContent/startup` (which appears to be what would be installed in `${CATALINA_HOME}/content/thredds` for a new installation) is missing the new `maxEntries` and `maxBloatFactor` setting for `FeatureCollection` discussed in #230.

I have not carefully checked the rest but even the order of the setting are different. I feel the two files should more closely resemble each other to avoid confusion about what settings are available to the users.

**Comment by haileyajohnson** [comment]
Neither is more up-to-date than the other, they are serving different purposes.
The `threddsConfig.xml` in the `startup` directory contains the minimum required properties and default settings to get a TDS up and running, whereas the `threddsConfig.xml` in the test directory is what we use to run our tests. It has more properties set so that we can test features and edge cases.
