### ISSUE TITLE
Looks like TDS v 5.4 applies scale_factor twice when serving data

### ISSUE THREAD

**Issue by rkouznetsov** [Unidata/tds#282]
Same file served from 4.6 and  5.4 results in different values:

```
#!/bin/sh         
 
## 
#Manifest-Version: 1.0
#Implementation-Title: THREDDS Data Server (TDS)
#Implementation-Version: 4.6.19-SNAPSHOT
#Built-By: hajohns
#Implementation-Vendor-Id: edu.ucar
#Implementation-URL: https://www.unidata.ucar.edu/software/tds/
#Created-By: Gradle 3.4.1
#Build-Jdk: 1.8.0_265
#Built-On: 2021-12-18T10:32:37-0500
#Implementation-Vendor: UCAR/Unidata                                                                                                                                                       
 
wget  "http://silam.fmi.fi/thredds/ncss/silam_glob_v5_7_1/files/SILAM-AQ-glob_v5_7_1_2022091200_001.nc4?var=cnc_O3_gas&vertCoord=10&accept=netcdf" -O thredds.old.nc
cdo outputtab,date,time,name,value -fldmean -selvar,cnc_O3_gas thredds.old.nc
 
##
#Manifest-Version: 1.0
#Implementation-Title: THREDDS Data Server (TDS)
#Implementation-Version: 5.4
#Implementation-Vendor-Id: edu.ucar
#Implementation-Vendor: UCAR/Unidata
#Implementation-URL: https://www.unidata.ucar.edu/software/tds/
#Created-By: Gradle 6.9.1
#Build-Jdk: 11.0.12
#Built-By: tdrwenski
#Built-On: 2022-07-01T12:01:49-0600
 
 
wget "http://thredds.silam.fmi.fi/thredds/ncss/grid/silam_glob_v5_7_1/files/SILAM-AQ-glob_v5_7_1_2022091200_001.nc4?var=cnc_O3_gas&vertCoord=10&accept=netcdf3" -O thredds.new.nc
cdo outputtab,date,time,name,value -fldmean -selvar,cnc_O3_gas thredds.new.nc
```
The field-mean values for cnc_O3_gas concentration reported by CDO are different by orders of magnitude, and the latter is wrong. Apparently both servers try to process scale_factor attribute of the variable in the original file.  5.4 just applies it twice.. 
Any clue? Thank you!

(you might need to replace 2022091200 with some date within 2-4 days ago, depending on when you test the case)

**Comment by rkouznetsov** [comment]
I have updated to  thredds-5.5-SNAPSHOT.war . The issue is still there. Probably, the reason is present `scale_factor`, but missing `add_offset` (which is perfectly legal, though not too common).

**Comment by rkouznetsov** [comment]
Sorry. I was wrong: both 4.6 and 5.4 apply scale_factor, but  5.4 does not clear the corresponding attribute after applying it.

Indeed, I would be more comfortable if ncss preserved both datatypes and packing information, since
packing is a destructive operation. We had to implement in SILAM a special procedure of unpacking the data, to handle some of the artifacts originating from packing. The unpacking procedure, as it has been described in CF, and as it is implemented in various NetCDF software is makes such handling impossible. E.g.,  as a result of "standard" packing-unpacking one can get negative values from an originally non-negative field (e.g. mixing ratio of something) .

**Comment by WeatherGod** [comment]
We are noticing this for the WCS service in 5.4 as well. More specifically, our source dataset has both `add_offset` and `scale_factor` attributes, which is getting preserved to the downloaded netcdf from WCS. Meanwhile, the data is correct if we use WCS to download a geotiff.

I should note that strictly speaking, the scale_factor and add_offset aren't applied twice, it is applied once upon save and is persisted through to the output product. Then when some other library such as xarray loads the file up, it applies the scaling again to the data that has already been scaled.

I looked at the differences between the geotiff and netcdf process in the WCS Coverage. The geotiff branch reads a GeoReferencedArray from a Coverage object, and then passes that to the geotiff writer (which handles that data in various ways based upon options). Meanwhile, the netcdf branch of WcsCoverage calls `getDataset()` of a WcsDataset object, and passes that to a `CFGridCoverageWriter` with a `NetcdfFormatWriter.Builder` passed to it as well.

I'm not exactly sure where the bug is and whether or not persisting the attributes should be desired behavior (I'm inclined to believe that it is). I'll also note that it appears that the opendap service does not suffer from this problem, but I haven't personally confirmed this (only that we noticed this when we switched from OpenDap to WCS in a project).

**Comment by WeatherGod** [comment]
I'm not very familiar with the netcdf-java api. Is there some sort of way for me to tell netcdf-java to *not* apply scaling and missing value replacement when loading a coverage? I'm digging all over and I can't seem to find such a thing.

As an alternative, I think I could write a patch that removes the `scale_factor` and `add_offset` attributes from the Coverage prior to WCS utilizing the netcdf writer. I worry though that this sets me up for a bug later when this gets patched in a more appropriate location. Depending on how such a patch is made, it could leave me with completely unscaled data output without appropriate attributes.

**Comment by rkouznetsov** [comment]
> I'm not very familiar with the netcdf-java api. Is there some sort of way for me to tell netcdf-java to not apply scaling and missing value replacement when loading a coverage?

Thank you! That would be the best.  I do not know much about netcdf-java. I hope such keys exist... 

As a side note, in NetCDF4-python the list of options needed to get an honest representation of an array from a file to memory is quite long, and has to be extended every time a new default 'convenience' feature added to the library.

**Comment by haileyajohnson** [comment]
@rkouznetsov you'll need to take up the NetCDF4-python issue on their [repo](https://github.com/Unidata/netcdf4-python)
I'm getting back into this issue right now though, my suspicion is still that we're hitting two implementations of scale and offset. Are the issues all occurring for netcdf4 and/or hdf5 datasets or have other data types hit it as well?

**Comment by WeatherGod** [comment]
Yeah, if this was python, I'd know what to do, but I think I am making some headway. Based on my notes from tracing the caching bug, I figured out how exactly the netcdf data is getting loaded (at least, for WCS/WMS, I don't know if it is the same for NCSS).

Around https://github.com/Unidata/tds/blob/main/tds/src/main/java/thredds/core/DatasetManager.java#L294 in the `openGridDataset()` method, the `NetcdfDataset.getDefaultEnhanceMode()` is supplied to the `enhance()` method. which is `EnhanceAll`. So, for all services that are using the `DatasetManager` approach of loading a catalog entry, all enhancements seem to be applied.

So, again, either the enhancement should strip the dataset of the attributes automatically, or the choice of `EnhanceAll` as the default that can't be overridden might be problematic. While all is fine for Geotiffs and WMS that aren't outputting netcdfs, that's only because the attributes aren't coming with them. I'm now leaning towards "It's a bug to leave the attributes in there", but I'm sure there are other considerations as well.

As an aside, I don't know if there is anything before this point that already took care of any enhancement settings that might have been specified in the NcML because the default is "None" according to the (spec)[https://docs.unidata.ucar.edu/netcdf-java/4.6/userguide/ncml/AnnotatedSchema4.html].

**Comment by WeatherGod** [comment]
@rkouznetsov Could you provide the output of `ncdump -h` on each of the two files? For bonus points, if you are able to open them in python using something like `xr.open_dataset('thredds.new.nc', mask_and_scale=False)` and report some statistics like mean and variance of the relevant variables from both of the data, we'll likely be able to see exactly whats coming out of thredds' ncss.

**Comment by haileyajohnson** [comment]
@WeatherGod the scale and offset are likely being applied both as enhancements and as filters, I'm working on testing my theory

**Comment by WeatherGod** [comment]
Well, here is a small python script I used to compare my netcdf and geotiff from WCS:
```
import xarray as xr
import numpy as np
import rioxarray as rio

da1 = xr.open_dataset('Downloads/H2O_NDVIAnomaly_NASA-Terra-MODIS_2022-11-17_2022-11-17.nc', mask_and_scale=False).ndvi_anom
da2 = rio.open_rasterio('Downloads/H2O_NDVIAnomaly_NASA-Terra-MODIS_2022-11-17.tif')

# Account for the "missing value" in geotiff
da2 = xr.where(da2 == da2.min(), np.nan, da2)

print("NetCDF:", da1)
print("GeoTIFF:", da2)

print("NetCDF:", float(da1.min()), float(da1.mean()), float(da1.max()))
print("GeoTIFF:", float(da2.min()), float(da2.mean()), float(da2.max()))
```
And here is the output

```
NetCDF: <xarray.DataArray 'ndvi_anom' (time: 1, lat: 493, lon: 782)>
[385526 values with dtype=float64]
Coordinates:
  * lon      (lon) float64 -12.31 -12.28 -12.26 -12.24 ... 5.221 5.244 5.266
  * time     (time) datetime64[ns] 2022-11-17
  * lat      (lat) float64 34.02 34.04 34.07 34.09 ... 45.02 45.05 45.07 45.09
Attributes:
    long_name:      Normalized Difference Vegetation Index Anomaly From 2001-...
    _FillValue:     255
    AREA_OR_POINT:  Area
    scale_factor:   0.008
    add_offset:     -1.0
    units:          1
    actual_range:   [-1.  1.]
    valid_range:    [  0 250]
    source:         USDA/FAS/IPAD NASA/GSFC/GIMMS Global Agricultural Monitor...
    missing_value:  255
GeoTIFF: <xarray.DataArray (band: 1, y: 493, x: 782)>
array([[[   nan,    nan,    nan, ...,    nan,    nan,    nan],
        [   nan,    nan,    nan, ...,    nan,    nan,    nan],
        [   nan,    nan,    nan, ..., -0.296,    nan,    nan],
        ...,
        [   nan,    nan,    nan, ...,  0.008,  0.   ,  0.008],
        [   nan,    nan,    nan, ...,  0.   ,  0.   , -0.016],
        [   nan,    nan,    nan, ...,  0.   ,  0.   ,  0.   ]]],
      dtype=float32)
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 -12.31 -12.28 -12.26 -12.24 ... 5.221 5.244 5.266
  * y            (y) float64 45.09 45.07 45.05 45.02 ... 34.09 34.07 34.04 34.02
    spatial_ref  int64 0
NetCDF: -0.832 0.018529007661571197 0.6799999999999999
GeoTIFF: -0.8320000171661377 0.01852901466190815 0.6800000071525574
```

Having xarray load without scaling and masking results in values that are nearly identical to the geotiff's. If I load it with scaling, then the output of the netcdf stats are:
```
NetCDF: -1.006656 -0.9998517679387074 -0.99456
```
which makes no sense for this particular variable.

**Comment by WeatherGod** [comment]
Yes, it totally makes sense for `cdo` to use the scale information it receives as input from ncss's output. That's part of how it the CDM is supposed to work in any particular library, be it cdo, xarray, netcdf-java. Once the scaling is applied, the attributes should be dropped since it is no longer true that such scaling needs to be applied anymore (or don't apply it and persist it). Notice that for xarray, if you load up the data with scaling, it drops the attributes:
```
<xarray.DataArray 'ndvi_anom' (time: 1, lat: 493, lon: 782)>
[385526 values with dtype=float64]
Coordinates:
  * lon      (lon) float64 -12.31 -12.28 -12.26 -12.24 ... 5.221 5.244 5.266
  * time     (time) datetime64[ns] 2022-11-17
  * lat      (lat) float64 34.02 34.04 34.07 34.09 ... 45.02 45.05 45.07 45.09
Attributes:
    long_name:      Normalized Difference Vegetation Index Anomaly From 2001-...
    AREA_OR_POINT:  Area
    units:          1
    actual_range:   [-1.  1.]
    valid_range:    [  0 250]
    source:         USDA/FAS/IPAD NASA/GSFC/GIMMS Global Agricultural Monitor...
```

**Comment by rkouznetsov** [comment]
@haileyajohnson 
> you'll need to take up the NetCDF4-python issue on their repo
Thank you!  It is not a bug, but a feature. By "honest" I mean the data that have been actually written in NetCDF including all attributes and exact values. In https://doi.org/10.5194/gmd-14-377-2021  I have put an example of errors originating from blind-eye packing-unpacking. Since then I got more such cases.

Undoing packing without dropping the packing attributes is definitely a bug.

However, I would appreciate if NCSS produced the original data without applying any 'enhancements' or filters.  An end user of the NCSS data should be capable of applying them all if needed, but the downloaded data can be e.g. archived. Then the unpacking done by NCSS is clearly a disservice. It might be unavoidable at the aggregation stage when packing attributes differ form file to file, but otherwise it should not be applied.

**Comment by haileyajohnson** [comment]
There is definitely a bug in the way the TDS ncss service is handling the packing attributes, I'm working on getting that fixed.

> However, I would appreciate if NCSS produced the original data without applying any 'enhancements' or filters. An end user of the NCSS data should be capable of applying them all if needed, but the downloaded data can be e.g. archived. Then the unpacking done by NCSS is clearly a disservice. It might be unavoidable at the aggregation stage when packing attributes differ form file to file, but otherwise it should not be applied.

I see your point, but the NCSS service is a pretty high level data client that handles returning subsets from different types of datasets (including, as mentioned, aggregations with different packing attributes), and in different formats, not all of which support return the packing attributes to the end user. So there are several cases in which not applying any enhancements/filters would produce nonsense (e.g., a grid as point csv request). On the other hand, I understand the use case for requesting the data with no transformation. We're not currently working on many new feature implementations, however if you'd like to see an option to request ncss data without enhancements and filters, feel free to open a feature request issue and hopefully either we or someone in the community will take that on.

**Comment by rkouznetsov** [comment]
Thank you!  
I'll try to put a feature request, with a slight hope that it gets some priority at some point.  Unfortunately, many people  believe that packing-unpacking is a harmless transformation (admittedly forgiving for many meteorological variables).  

More permanent solution would be to deprecate packing. At least in CF conventions. In modern world with precision-trimming and NetCDF4 compression there is absolutely no reason to damage new datasets with packing and hide the damage with unpacking.

In my case the `scale_factor` attribute was used for fast unit-conversion of the data that were stored with trimmed precision. Looks like it was not a good idea, given the tendency of data-handling software to unpack everything without a notice.

**Comment by haileyajohnson** [comment]
This is the last thing we're working on for the 5.5 release, and should be available shortly!

**Comment by rkouznetsov** [comment]
Thank you! Looking forward to test it!
