### ISSUE TITLE
Feature Request: Prometheus Exporter

### ISSUE THREAD

**Issue by nathanlcarlson** [Unidata/tds#58]
## Feature Request

The monitoring tool [Prometheus](https://prometheus.io/docs/introduction/overview/) is gaining popularity and is being adopted by major software projects, [Solr](http://lucene.apache.org/solr/guide/7_7/monitoring-solr-with-prometheus-and-grafana.html) and [JupyterHub](https://jupyterhub.readthedocs.io/en/stable/changelog.html?highlight=prometheus), for example.

The model is a central Prometheus server "scrapes" (pulls) from "exporters" via HTTP and stores the metrics collected. Exporters are generally integrated into services. Thredds is an excellent candidate for an exporter.

Prometheus sets a number of standards and strongly recommends they are followed. They lay out the [Best Practices for Exporters](https://prometheus.io/docs/instrumenting/writing_exporters/) nicely. With the existence of 'tdsMonitor' this may be an easy feature to add. I am not familiar with an inner workings of TDS, just a guess.

**Comment by lesserwhirls** [comment]
`TdsMonitor` is pretty basic metrics-wise, in that it reads the Tomcat (predefined format based on our docs) and TDS logs into memory and does some basic calculations. None of that is done server side, so there is no increased load on the server due to metrics tracking. It's good for debugging requests though, and is still overall useful, albeit a bit unrefined.

Prometheus looks pretty interesting. I could see a few ways it could be used with the TDS, but the question would be what kind of metrics would you want to collect? I don't know that it would be baked into the TDS war, but perhaps as an optional, pluggable service.

**Comment by 1naboki1** [comment]
I would propose metrics like

- Outgoing / Incoming HTTP requests for specific services
- Processing time for the OPeNDAP Dataset Access Form
- Resources
