### ISSUE TITLE
Why is TDS v5.0 still in beta version?

### ISSUE THREAD

**Issue by Chilipp** [Unidata/tds#63]
Hello wonderful developers at unidata!

We would like to install a THREDDS server in our institute and are wondering about the release policy of TDS. Can we savely install the latest beta of TDS ([v5.0.0-beta7](https://github.com/Unidata/tds/releases/tag/v5.0.0-beta7)) on our server? We would like to use this due to the new and better features (e.g. the upload and download functionalities). Or should we better use 4.6 because it is the latest stable release and therefore (eventually) more secure?

A general question: According to the blog, [version 5 should have been released in May 2018](https://www.unidata.ucar.edu/blogs/news/entry/coming-soon-public-beta-of) already, but we could not find any further information about the progress. Can you say anything about the progress of making a stable v5.0.0 release? 

Best regards and thanks a lot for your great services to the netCDF-Community!

**Comment by lesserwhirls** [comment]
Greetings @Chilipp! Thank you for reaching out, and many apologies for the delay.

> We would like to install a THREDDS server in our institute and are wondering about the release policy of TDS. Can we safely install the latest beta of TDS (v5.0.0-beta7) on our server?

Many sites are running TDS 5 in beta. There are a few outstanding items that need to be complete in order to make sure TDS 5 is feature complete with respect to TDS 4. Specifically, we still need to enable WMS customization, and there are a one or two types of variables that the NetcdfSubsetService does not support yet (irregular discontiguous spaced interval variables, mostly seen in GRIB, I believe). Some of these are on the TDS side (like WMS customization), and some are on the netCDF-Java side (like support for irregular discontiguous interval variable subsetting).

> We would like to use this due to the new and better features (e.g. the upload and download functionalities).

The upload feature is, essentially, a proof of concept and I would *strongly recommend* not using it in production. It essentially allows uploads to a single, specific directory, and provides an automatic `datasetScan` on top of that directory. In a tightly controlled test environment, this could be useful in vetting potential new files, but the upload step is probably the least time consuming part of vetting a new dataset.

> Or should we better use 4.6 because it is the latest stable release and therefore (eventually) more secure?

As long as you are using the latest release, security should be similar. A lot of the TDS security comes down to the security of the servlet container you are running. We do run nightly scans of both code bases (4.6, 5.0) using some of the OWASP tools, and upgrade vulnerable dependencies  as quickly as we can.

> A general question: According to the blog, version 5 should have been released in May 2018 already, but we could not find any further information about the progress. Can you say anything about the progress of making a stable v5.0.0 release?

Yes, that's a failing on my part, and I greatly apologize for that. At the time the blog post was written, we had essentially two developers working on netCDF-Java and TDS (one of us full time). Shortly after the post, the full time developer moved on to pursue other opportunities. By the end of 2018, we hired a new developer, but unfortunately he also left to pursue other opportunities after just under a year of service. We've been in the process of hiring a new developer since January, and are continuing our search. Given the current uncertain times, I'm uncertain of our chances of success, but with any luck, we will have a job posting soon. None of this excuses the lack of release, but it might help explain the situation a bit. At any rate, it is my goal to have a TDS 5.0.0 stable release by the end of May, if not sooner.

**Comment by Chilipp** [comment]
Thanks a lot @lesserwhirls for this detailed explanation! This is of great help :smiley: We'll use TDS 5 then and look forward to the stable release.
